import { jsPDF } from "jspdf";
import type {
  BetterCompetitorAd,
  CompetitorAdAnalysis,
} from "@/lib/competitor-ad/types";
import { getCompetitorScoreColor } from "@/lib/competitor-ad/scores";

const BRAND_NAME = "Advora AI";
const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function hexToRgb(hex: string): [number, number, number] {
  const normalized = hex.replace("#", "");
  const r = parseInt(normalized.slice(0, 2), 16);
  const g = parseInt(normalized.slice(2, 4), 16);
  const b = parseInt(normalized.slice(4, 6), 16);
  return [r, g, b];
}

function addHeader(doc: jsPDF, title: string) {
  doc.setFillColor(10, 6, 24);
  doc.rect(0, 0, PAGE_WIDTH, 36, "F");
  doc.setTextColor(34, 211, 238);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(BRAND_NAME, MARGIN, 16);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(title, MARGIN, 28);
  doc.setTextColor(30, 30, 30);
}

function addFooter(doc: jsPDF, pageNumber: number) {
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by ${BRAND_NAME} · Page ${pageNumber}`,
    MARGIN,
    290
  );
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 275) {
    doc.addPage();
    addFooter(doc, doc.getNumberOfPages());
    return 44;
  }
  return y;
}

function addSectionTitle(doc: jsPDF, y: number, title: string): number {
  y = ensureSpace(doc, y, 14);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(88, 28, 135);
  doc.text(title, MARGIN, y);
  return y + 8;
}

function addWrappedText(
  doc: jsPDF,
  y: number,
  text: string,
  fontSize = 10,
  indent = 0
): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(fontSize);
  doc.setTextColor(50, 50, 50);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH - indent);
  for (const line of lines) {
    y = ensureSpace(doc, y, 6);
    doc.text(line, MARGIN + indent, y);
    y += 5;
  }
  return y + 2;
}

function addBulletList(doc: jsPDF, y: number, items: string[]): number {
  for (const item of items) {
    y = ensureSpace(doc, y, 8);
    y = addWrappedText(doc, y, `• ${item}`, 10, 4);
  }
  return y + 2;
}

function addScoreLine(
  doc: jsPDF,
  y: number,
  label: string,
  score: number
): number {
  y = ensureSpace(doc, y, 8);
  const [r, g, b] = hexToRgb(getCompetitorScoreColor(score));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`${label}:`, MARGIN, y);
  doc.setTextColor(r, g, b);
  doc.text(`${score}/100`, MARGIN + 70, y);
  return y + 7;
}

export function generateCompetitorPdfReport(
  analysis: CompetitorAdAnalysis,
  betterAd?: BetterCompetitorAd | null
): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const { scores, suggestions, score_explanations: explanations } = analysis;

  addHeader(doc, "Competitor Ad Analysis Report");

  let y = 44;

  y = addSectionTitle(doc, y, "Overview");
  y = addWrappedText(doc, y, `Brand: ${analysis.brand || "Unknown"}`);
  y = addWrappedText(doc, y, `Product: ${analysis.product || "Unknown"}`);
  y = addWrappedText(doc, y, `Platform: ${analysis.platform || "Unknown"}`);
  y = addWrappedText(doc, y, `Objective: ${analysis.ad_objective || "Not detected"}`);
  y = addWrappedText(
    doc,
    y,
    `Detection Confidence: ${analysis.analysis_confidence.percent}% (${analysis.analysis_confidence.level})`
  );

  y = addSectionTitle(doc, y, "Scores");
  y = addScoreLine(doc, y, "Overall Score", scores.overall_score);
  y = addScoreLine(doc, y, "Hook Score", scores.hook_score);
  if (explanations.hook_score) {
    y = addWrappedText(doc, y, explanations.hook_score, 9, 4);
  }
  y = addScoreLine(doc, y, "CTA Score", scores.cta_score);
  if (explanations.cta_score) {
    y = addWrappedText(doc, y, explanations.cta_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Visual Score", scores.visual_score);
  if (explanations.visual_score) {
    y = addWrappedText(doc, y, explanations.visual_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Copy Score", scores.copy_score);
  if (explanations.copy_score) {
    y = addWrappedText(doc, y, explanations.copy_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Trust Score", scores.trust_score);
  if (explanations.trust_score) {
    y = addWrappedText(doc, y, explanations.trust_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Offer Score", scores.offer_score);
  if (explanations.offer_score) {
    y = addWrappedText(doc, y, explanations.offer_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Psychology Score", scores.psychology_score);
  if (explanations.psychology_score) {
    y = addWrappedText(doc, y, explanations.psychology_score, 9, 4);
  }
  y = addScoreLine(doc, y, "Urgency / FOMO", analysis.urgency_fomo_score);
  if (explanations.urgency_fomo_score) {
    y = addWrappedText(doc, y, explanations.urgency_fomo_score, 9, 4);
  }

  y = addSectionTitle(doc, y, "Audience & Psychology");
  y = addBulletList(doc, y, analysis.target_audience);
  y = addWrappedText(doc, y, "Emotional triggers:");
  y = addBulletList(doc, y, analysis.emotional_triggers);
  y = addWrappedText(doc, y, "Marketing psychology:");
  y = addBulletList(doc, y, analysis.marketing_psychology);

  y = addSectionTitle(doc, y, "Detailed Analysis");
  y = addWrappedText(doc, y, `Hook: ${analysis.hook_analysis}`);
  y = addWrappedText(doc, y, `CTA: ${analysis.cta_analysis}`);
  y = addWrappedText(doc, y, `Offer: ${analysis.offer_quality}`);
  y = addWrappedText(doc, y, `Visual: ${analysis.visual_quality}`);
  y = addWrappedText(doc, y, `Copy: ${analysis.copywriting_quality}`);

  y = addSectionTitle(doc, y, "Strengths");
  y = addBulletList(doc, y, suggestions.what_makes_successful);

  y = addSectionTitle(doc, y, "Weaknesses");
  y = addBulletList(doc, y, suggestions.weaknesses);

  y = addSectionTitle(doc, y, "How to Outperform");
  y = addBulletList(doc, y, suggestions.how_to_outperform);

  y = addSectionTitle(doc, y, "Performance Insights");
  const insights = analysis.performance_insights;
  y = addWrappedText(
    doc,
    y,
    `Conversion Potential: ${insights.conversion_potential.value} — ${insights.conversion_potential.reasoning}`
  );
  y = addWrappedText(
    doc,
    y,
    `Estimated CTR: ${insights.estimated_ctr.value} — ${insights.estimated_ctr.reasoning}`
  );
  y = addWrappedText(
    doc,
    y,
    `Scroll Stop Rate: ${insights.scroll_stop_rate.value} — ${insights.scroll_stop_rate.reasoning}`
  );
  y = addWrappedText(
    doc,
    y,
    `Purchase Intent: ${insights.purchase_intent.value} — ${insights.purchase_intent.reasoning}`
  );
  y = addWrappedText(
    doc,
    y,
    `Engagement Probability: ${insights.engagement_probability.value} — ${insights.engagement_probability.reasoning}`
  );

  y = addSectionTitle(doc, y, "AI Recommendations");
  y = addWrappedText(doc, y, "Better hooks:");
  y = addBulletList(doc, y, suggestions.better_hook_suggestions);
  y = addWrappedText(doc, y, "Better CTAs:");
  y = addBulletList(doc, y, suggestions.better_cta_suggestions);
  y = addWrappedText(doc, y, "Better offers:");
  y = addBulletList(doc, y, suggestions.better_offer_suggestions);

  const improved = analysis.improved_version;
  if (improved.why_better) {
    y = addSectionTitle(doc, y, "Advora AI Improved Version (Predicted)");
    y = addWrappedText(
      doc,
      y,
      `Predicted improvement: +${improved.overall_improvement} overall score`
    );
    y = addWrappedText(doc, y, improved.why_better);
  }

  if (betterAd) {
    y = addSectionTitle(doc, y, "Generated Better Ad");
    if (betterAd.hooks.length > 0) {
      y = addWrappedText(doc, y, "Hooks:");
      y = addBulletList(doc, y, betterAd.hooks);
    }
    if (betterAd.headlines.length > 0) {
      y = addWrappedText(doc, y, "Headlines:");
      y = addBulletList(doc, y, betterAd.headlines);
    }
    if (betterAd.captions.length > 0) {
      y = addWrappedText(doc, y, "Captions:");
      y = addBulletList(doc, y, betterAd.captions);
    }
    if (betterAd.ctas.length > 0) {
      y = addWrappedText(doc, y, "CTAs:");
      y = addBulletList(doc, y, betterAd.ctas);
    }
    if (betterAd.offers.length > 0) {
      y = addWrappedText(doc, y, "Offers:");
      y = addBulletList(doc, y, betterAd.offers);
    }
    if (betterAd.ugcScript) {
      y = addWrappedText(doc, y, `UGC Script:\n${betterAd.ugcScript}`);
    }
  }

  addFooter(doc, 1);
  const totalPages = doc.getNumberOfPages();
  for (let page = 2; page <= totalPages; page += 1) {
    doc.setPage(page);
    addFooter(doc, page);
  }

  const safeBrand = (analysis.brand || "competitor-ad")
    .replace(/[^a-z0-9]+/gi, "-")
    .toLowerCase();
  doc.save(`advora-competitor-analysis-${safeBrand}.pdf`);
}
